// Aranabilir düğün destinasyonları. IANA listesinde olmayan adlarla (ülke, bölge, tatil yeri) arama sağlar.
// popular: true olanlar liste açılınca en üstte görünür.
const COUNTRY_ALIASES = {
  "United Kingdom": ["UK", "England", "Great Britain", "Britain"],
  "United States": ["USA", "US", "America"],
  "United Arab Emirates": ["UAE"],
  "Turkey": ["Türkiye", "Turkiye"],
  "Netherlands": ["Holland"],
  "Czech Republic": ["Czechia"],
};

const PLACES = [
  // Popüler
  { name: "London", country: "United Kingdom", zone: "Europe/London", popular: true },
  { name: "New York", country: "United States", zone: "America/New_York", popular: true },
  { name: "Los Angeles", country: "United States", zone: "America/Los_Angeles", popular: true },
  { name: "Chicago", country: "United States", zone: "America/Chicago", popular: true },
  { name: "Toronto", country: "Canada", zone: "America/Toronto", popular: true },
  { name: "Sydney", country: "Australia", zone: "Australia/Sydney", popular: true },
  { name: "Paris", country: "France", zone: "Europe/Paris", popular: true },
  { name: "Rome", country: "Italy", zone: "Europe/Rome", popular: true },
  { name: "Santorini", country: "Greece", zone: "Europe/Athens", popular: true },
  { name: "Istanbul", country: "Turkey", zone: "Europe/Istanbul", popular: true },
  { name: "Dubai", country: "United Arab Emirates", zone: "Asia/Dubai", popular: true },
  { name: "Bali", country: "Indonesia", zone: "Asia/Makassar", popular: true },
  { name: "Cancún", country: "Mexico", zone: "America/Cancun", popular: true },
  { name: "Hawaii", country: "United States", zone: "Pacific/Honolulu", popular: true },
  { name: "Dublin", country: "Ireland", zone: "Europe/Dublin", popular: true },
  { name: "Lisbon", country: "Portugal", zone: "Europe/Lisbon", popular: true },

  // Birleşik Krallık & İrlanda
  { name: "Edinburgh", country: "United Kingdom", zone: "Europe/London", aliases: ["Scotland"] },
  { name: "Cardiff", country: "United Kingdom", zone: "Europe/London", aliases: ["Wales"] },
  { name: "Belfast", country: "United Kingdom", zone: "Europe/London", aliases: ["Northern Ireland"] },
  { name: "Manchester", country: "United Kingdom", zone: "Europe/London" },
  { name: "Cotswolds", country: "United Kingdom", zone: "Europe/London" },

  // Avrupa
  { name: "Florence", country: "Italy", zone: "Europe/Rome", aliases: ["Tuscany"] },
  { name: "Amalfi Coast", country: "Italy", zone: "Europe/Rome", aliases: ["Positano"] },
  { name: "Lake Como", country: "Italy", zone: "Europe/Rome" },
  { name: "Venice", country: "Italy", zone: "Europe/Rome" },
  { name: "Sicily", country: "Italy", zone: "Europe/Rome" },
  { name: "Athens", country: "Greece", zone: "Europe/Athens" },
  { name: "Mykonos", country: "Greece", zone: "Europe/Athens" },
  { name: "Crete", country: "Greece", zone: "Europe/Athens" },
  { name: "Barcelona", country: "Spain", zone: "Europe/Madrid" },
  { name: "Madrid", country: "Spain", zone: "Europe/Madrid" },
  { name: "Mallorca", country: "Spain", zone: "Europe/Madrid", aliases: ["Majorca"] },
  { name: "Ibiza", country: "Spain", zone: "Europe/Madrid" },
  { name: "Canary Islands", country: "Spain", zone: "Atlantic/Canary", aliases: ["Tenerife", "Gran Canaria"] },
  { name: "Provence", country: "France", zone: "Europe/Paris" },
  { name: "Nice", country: "France", zone: "Europe/Paris", aliases: ["French Riviera", "Côte d'Azur"] },
  { name: "Porto", country: "Portugal", zone: "Europe/Lisbon" },
  { name: "Algarve", country: "Portugal", zone: "Europe/Lisbon" },
  { name: "Madeira", country: "Portugal", zone: "Atlantic/Madeira" },
  { name: "Dubrovnik", country: "Croatia", zone: "Europe/Zagreb" },
  { name: "Split", country: "Croatia", zone: "Europe/Zagreb" },
  { name: "Amsterdam", country: "Netherlands", zone: "Europe/Amsterdam" },
  { name: "Berlin", country: "Germany", zone: "Europe/Berlin" },
  { name: "Munich", country: "Germany", zone: "Europe/Berlin" },
  { name: "Vienna", country: "Austria", zone: "Europe/Vienna" },
  { name: "Zurich", country: "Switzerland", zone: "Europe/Zurich" },
  { name: "Prague", country: "Czech Republic", zone: "Europe/Prague" },
  { name: "Budapest", country: "Hungary", zone: "Europe/Budapest" },
  { name: "Warsaw", country: "Poland", zone: "Europe/Warsaw" },
  { name: "Copenhagen", country: "Denmark", zone: "Europe/Copenhagen" },
  { name: "Stockholm", country: "Sweden", zone: "Europe/Stockholm" },
  { name: "Oslo", country: "Norway", zone: "Europe/Oslo" },
  { name: "Reykjavik", country: "Iceland", zone: "Atlantic/Reykjavik" },
  { name: "Malta", country: "Malta", zone: "Europe/Malta" },
  { name: "Cyprus", country: "Cyprus", zone: "Asia/Nicosia" },
  { name: "Antalya", country: "Turkey", zone: "Europe/Istanbul" },
  { name: "Bodrum", country: "Turkey", zone: "Europe/Istanbul" },
  { name: "Cappadocia", country: "Turkey", zone: "Europe/Istanbul" },
  { name: "Bucharest", country: "Romania", zone: "Europe/Bucharest" },
  { name: "Sofia", country: "Bulgaria", zone: "Europe/Sofia" },
  { name: "Kyiv", country: "Ukraine", zone: "Europe/Kyiv", aliases: ["Kiev"] },
  { name: "Tbilisi", country: "Georgia", zone: "Asia/Tbilisi" },

  // Orta Doğu & Afrika
  { name: "Abu Dhabi", country: "United Arab Emirates", zone: "Asia/Dubai" },
  { name: "Doha", country: "Qatar", zone: "Asia/Qatar" },
  { name: "Riyadh", country: "Saudi Arabia", zone: "Asia/Riyadh" },
  { name: "Tel Aviv", country: "Israel", zone: "Asia/Jerusalem" },
  { name: "Beirut", country: "Lebanon", zone: "Asia/Beirut" },
  { name: "Cairo", country: "Egypt", zone: "Africa/Cairo" },
  { name: "Marrakech", country: "Morocco", zone: "Africa/Casablanca" },
  { name: "Cape Town", country: "South Africa", zone: "Africa/Johannesburg" },
  { name: "Nairobi", country: "Kenya", zone: "Africa/Nairobi" },
  { name: "Lagos", country: "Nigeria", zone: "Africa/Lagos" },
  { name: "Mauritius", country: "Mauritius", zone: "Indian/Mauritius" },
  { name: "Seychelles", country: "Seychelles", zone: "Indian/Mahe" },

  // Asya & Okyanusya
  { name: "Maldives", country: "Maldives", zone: "Indian/Maldives" },
  { name: "Mumbai", country: "India", zone: "Asia/Kolkata" },
  { name: "Delhi", country: "India", zone: "Asia/Kolkata", aliases: ["New Delhi"] },
  { name: "Goa", country: "India", zone: "Asia/Kolkata" },
  { name: "Udaipur", country: "India", zone: "Asia/Kolkata", aliases: ["Jaipur", "Rajasthan"] },
  { name: "Phuket", country: "Thailand", zone: "Asia/Bangkok", aliases: ["Koh Samui"] },
  { name: "Bangkok", country: "Thailand", zone: "Asia/Bangkok" },
  { name: "Singapore", country: "Singapore", zone: "Asia/Singapore" },
  { name: "Kuala Lumpur", country: "Malaysia", zone: "Asia/Kuala_Lumpur" },
  { name: "Jakarta", country: "Indonesia", zone: "Asia/Jakarta" },
  { name: "Manila", country: "Philippines", zone: "Asia/Manila" },
  { name: "Hanoi", country: "Vietnam", zone: "Asia/Bangkok" },
  { name: "Ho Chi Minh City", country: "Vietnam", zone: "Asia/Ho_Chi_Minh", aliases: ["Saigon"] },
  { name: "Hong Kong", country: "Hong Kong", zone: "Asia/Hong_Kong" },
  { name: "Shanghai", country: "China", zone: "Asia/Shanghai", aliases: ["Beijing"] },
  { name: "Taipei", country: "Taiwan", zone: "Asia/Taipei" },
  { name: "Tokyo", country: "Japan", zone: "Asia/Tokyo", aliases: ["Kyoto", "Osaka"] },
  { name: "Seoul", country: "South Korea", zone: "Asia/Seoul" },
  { name: "Melbourne", country: "Australia", zone: "Australia/Melbourne" },
  { name: "Brisbane", country: "Australia", zone: "Australia/Brisbane", aliases: ["Gold Coast"] },
  { name: "Perth", country: "Australia", zone: "Australia/Perth" },
  { name: "Adelaide", country: "Australia", zone: "Australia/Adelaide" },
  { name: "Auckland", country: "New Zealand", zone: "Pacific/Auckland", aliases: ["Queenstown", "Wellington"] },
  { name: "Fiji", country: "Fiji", zone: "Pacific/Fiji" },
  { name: "Bora Bora", country: "French Polynesia", zone: "Pacific/Tahiti", aliases: ["Tahiti"] },

  // Kuzey Amerika
  { name: "Maui", country: "United States", zone: "Pacific/Honolulu", aliases: ["Honolulu", "Oahu"] },
  { name: "San Francisco", country: "United States", zone: "America/Los_Angeles", aliases: ["Napa Valley"] },
  { name: "Las Vegas", country: "United States", zone: "America/Los_Angeles" },
  { name: "San Diego", country: "United States", zone: "America/Los_Angeles" },
  { name: "Seattle", country: "United States", zone: "America/Los_Angeles" },
  { name: "Denver", country: "United States", zone: "America/Denver", aliases: ["Colorado"] },
  { name: "Phoenix", country: "United States", zone: "America/Phoenix", aliases: ["Arizona", "Scottsdale"] },
  { name: "Dallas", country: "United States", zone: "America/Chicago", aliases: ["Texas"] },
  { name: "Houston", country: "United States", zone: "America/Chicago" },
  { name: "Austin", country: "United States", zone: "America/Chicago" },
  { name: "Nashville", country: "United States", zone: "America/Chicago", aliases: ["Tennessee"] },
  { name: "New Orleans", country: "United States", zone: "America/Chicago" },
  { name: "Miami", country: "United States", zone: "America/New_York", aliases: ["Florida"] },
  { name: "Boston", country: "United States", zone: "America/New_York" },
  { name: "Washington, D.C.", country: "United States", zone: "America/New_York", aliases: ["Washington DC"] },
  { name: "Atlanta", country: "United States", zone: "America/New_York" },
  { name: "Charleston", country: "United States", zone: "America/New_York", aliases: ["Savannah"] },
  { name: "Philadelphia", country: "United States", zone: "America/New_York" },
  { name: "Anchorage", country: "United States", zone: "America/Anchorage", aliases: ["Alaska"] },
  { name: "Vancouver", country: "Canada", zone: "America/Vancouver" },
  { name: "Montreal", country: "Canada", zone: "America/Toronto", aliases: ["Ottawa", "Quebec"] },
  { name: "Calgary", country: "Canada", zone: "America/Edmonton", aliases: ["Banff"] },
  { name: "Halifax", country: "Canada", zone: "America/Halifax" },
  { name: "Mexico City", country: "Mexico", zone: "America/Mexico_City" },
  { name: "Tulum", country: "Mexico", zone: "America/Cancun", aliases: ["Playa del Carmen", "Riviera Maya"] },
  { name: "Los Cabos", country: "Mexico", zone: "America/Mazatlan", aliases: ["Cabo San Lucas"] },

  // Karayipler, Orta & Güney Amerika
  { name: "Punta Cana", country: "Dominican Republic", zone: "America/Santo_Domingo" },
  { name: "Jamaica", country: "Jamaica", zone: "America/Jamaica", aliases: ["Montego Bay"] },
  { name: "Bahamas", country: "Bahamas", zone: "America/Nassau", aliases: ["Nassau"] },
  { name: "Aruba", country: "Aruba", zone: "America/Aruba" },
  { name: "Puerto Rico", country: "Puerto Rico", zone: "America/Puerto_Rico", aliases: ["San Juan"] },
  { name: "St. Lucia", country: "Saint Lucia", zone: "America/St_Lucia" },
  { name: "Costa Rica", country: "Costa Rica", zone: "America/Costa_Rica" },
  { name: "São Paulo", country: "Brazil", zone: "America/Sao_Paulo", aliases: ["Rio de Janeiro"] },
  { name: "Buenos Aires", country: "Argentina", zone: "America/Argentina/Buenos_Aires" },
  { name: "Lima", country: "Peru", zone: "America/Lima" },
  { name: "Bogotá", country: "Colombia", zone: "America/Bogota", aliases: ["Cartagena"] },
];

if (typeof module === "object" && module.exports) module.exports = { PLACES, COUNTRY_ALIASES };
